# Generated by Django 4.2.4 on 2023-08-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0003_alter_tguser_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callrequest',
            name='message',
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='status',
            field=models.CharField(choices=[('0', 'Закрытая'), ('1', 'Новая'), ('2', 'В процессе'), ('3', 'Не дозвонился')], default='1', max_length=30, verbose_name='статус'),
        ),
    ]
