# Generated by Django 4.2.4 on 2023-08-06 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0004_remove_callrequest_message_alter_callrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, validators=[django.core.validators.RegexValidator(message="The phone number must be specified in the following format: '+79012345678'.", regex='^\\+\\d{11,20}')], verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='username',
            field=models.CharField(max_length=255, unique=True, verbose_name='username'),
        ),
    ]
