# Generated by Django 4.2.4 on 2023-08-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0005_alter_tguser_fullname_alter_tguser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='username',
            field=models.CharField(max_length=255, verbose_name='username'),
        ),
    ]
