# Generated by Django 4.2.4 on 2023-08-07 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0007_alter_callrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TGMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('status', models.CharField(choices=[('0', 'Отвечено'), ('1', 'Новое'), ('2', 'Прочитано'), ('3', 'Отложено'), ('4', 'Спам (заблокировать)')], default='1', max_length=30, verbose_name='статус')),
                ('text', models.TextField(max_length=10000, verbose_name='текст обращения')),
                ('comment', models.TextField(blank=True, max_length=10000, null=True, verbose_name='комментарий администратора')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='app_telegram.tguser', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
    ]
