# Generated by Django 4.2.4 on 2023-08-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0008_tgmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tguser',
            name='username',
        ),
        migrations.AlterField(
            model_name='tguser',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='телефон'),
        ),
    ]
