# Generated by Django 4.2.4 on 2023-08-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0009_remove_tguser_username_alter_tguser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='забанен'),
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='status',
            field=models.CharField(choices=[('0', 'Закрытая'), ('1', 'Новая'), ('2', 'В процессе'), ('3', 'Не дозвонился'), ('4', 'Перезвонить'), ('5', 'Спам (заблокировать)')], default='1', max_length=30, verbose_name='статус'),
        ),
        migrations.DeleteModel(
            name='TGMessage',
        ),
    ]
