# Generated by Django 4.2.4 on 2023-08-05 16:51

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='заголовок')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('use_dollars', models.BooleanField(default=True, verbose_name='использовать цену в долларах (если нет, укажите цену в рублях)')),
                ('price_dollar', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True, verbose_name='цена в долларах')),
                ('price_rub', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True, verbose_name='цена в рублях')),
                ('available', models.CharField(choices=[('no', 'Не доступно'), ('stock', 'В наличии'), ('order', 'Под заказ')], default='stock', max_length=30, verbose_name='наличие')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('category', mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='app_products.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'товар / услуга',
                'verbose_name_plural': 'товары / услуги',
                'ordering': ('-created',),
            },
        ),
    ]
