# Generated by Django 4.2.4 on 2023-08-05 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0003_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='характеристика')),
            ],
            options={
                'verbose_name': 'имя характеристики',
                'verbose_name_plural': 'имена характеристик',
            },
        ),
        migrations.CreateModel(
            name='ParameterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, unique=True, verbose_name='значение')),
            ],
            options={
                'verbose_name': 'значение характеристики',
                'verbose_name_plural': 'значения характеристик',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter', to='app_products.parametername', verbose_name='название')),
                ('products', models.ManyToManyField(blank=True, to='app_products.product', verbose_name='продукты')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter', to='app_products.parametervalue', verbose_name='значение')),
            ],
            options={
                'verbose_name': 'характеристика',
                'verbose_name_plural': 'характеристики',
            },
        ),
    ]
