# Generated by Django 4.2.4 on 2023-08-18 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0004_parametername_parametervalue_parameter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parameter',
        ),
        migrations.DeleteModel(
            name='ParameterName',
        ),
        migrations.DeleteModel(
            name='ParameterValue',
        ),
    ]
