# Generated by Django 4.2.4 on 2023-08-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=55, null=True, verbose_name='название компании')),
                ('description', models.TextField(blank=True, null=True, verbose_name='краткое описание')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='номер телефона для связи')),
                ('phone_messengers', models.CharField(blank=True, max_length=20, null=True, verbose_name='номер телефона (мессенджеры)')),
            ],
            options={
                'verbose_name': 'компания',
                'verbose_name_plural': 'компания',
            },
        ),
    ]
