# Generated by Django 4.2.4 on 2023-08-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0002_currencysettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'настройка администраторов',
                'verbose_name_plural': 'настройки администраторов',
            },
        ),
    ]
