# Generated by Django 4.2.4 on 2023-08-08 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0003_adminssettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=85, verbose_name='имя')),
                ('phone_number', models.CharField(max_length=20, verbose_name='номер телефона')),
                ('tg_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='id Telegram')),
                ('username', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='username Telegram')),
                ('admins_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_item', to='app_settings.adminssettings', verbose_name='настройки администраторов')),
            ],
            options={
                'verbose_name': 'настройка администратора',
                'verbose_name_plural': 'настройки администратора',
            },
        ),
    ]
