# Generated by Django 4.2.4 on 2023-08-09 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0004_adminitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencysettings',
            old_name='exchange_rate',
            new_name='fixed_exchange_rate',
        ),
        migrations.AddField(
            model_name='currencysettings',
            name='current_rate',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True, verbose_name='текущий курс доллара'),
        ),
        migrations.AddField(
            model_name='currencysettings',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 18, 35, 20, 754960), verbose_name='дата обновления'),
        ),
    ]
