# Generated by Django 4.2.4 on 2023-08-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0005_rename_exchange_rate_currencysettings_fixed_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencysettings',
            name='fixed_exchange_rate',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True, verbose_name='задать фиксированный курс доллара'),
        ),
        migrations.AlterField(
            model_name='currencysettings',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='дата обновления'),
        ),
    ]
